version: "3.9"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules 
      - /app/.next 
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8000
    command: npm run dev 
    
  backend:
      build:
        context: ./back
        dockerfile: Dockerfile
      env_file:
        - .env
      ports:
        - "8000:8000"
      volumes:
        - ./back:/app
      environment:
        OLLAMA_URL: http://ollama:11434/api/generate
      command: uvicorn main:app --host 0.0.0.0 --port 8000
      depends_on:
        ollama:
          condition: service_healthy

  
  ollama:
    image: alpine/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./Modelfile:/Modelfile
      - ./ollama_entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 20s
      timeout: 5s
      retries: 12
      start_period: 120s
    
volumes:
  ollama_data: